### PR TITLE
Update version in package.json

### PR DESCRIPTION
**Pull request by rodrigobdz**
Latest version in npmjs is 1.0.5. Point to latest version published.

### CODE REVIEW

**Comment by giannif** [comment]
@rodrigobdz your comment looks correct but the package.json has `1.0.05`. Containing an extra `0` before the 5. 

When bumping versions `npm version major|minor|patch` can be used on the command line

**Comment by rodrigobdz** [comment]
>@rodrigobdz your comment looks correct but the package.json has `1.0.05`. Containing an extra `0` before the 5.  ...

@giannif meaning that it should not have the leading 0 before the 5? I just updated the package.json manually because I noticed that it was pointing to an outdated version.

**Comment by giannif** [comment]
Yes it should not have the extra 0. I’ve never seen a package version declared that way and want to stick with convention so semver works as expected

**Comment by rodrigobdz** [comment]
@giannif I agree with you. I played around with semver and it does not accept leading zeros as in `1.0.05`.

semver node

semver cli

**Pull request merged**
