### PR TITLE
SDK returns null for webp, removing _url fixes the issue

### PR DESCRIPTION
**Pull request by jeffpearsall**

### CODE REVIEW

**Comment by rodrigobdz** [comment]
Related to #21. Cause: [API](https://developers.giphy.com/docs/) was updated.

**Comment by cosmocochrane1** [comment]
@rodrigobdz Awesome

**Comment by jeffpearsall** [comment]
@cosmocochrane1 would this fix be part of a bigger issue? Trying to decide if we need to fork the repo to launch the integration in our app or just hang tight for the fix.

**Comment by cosmocochrane1** [comment]
@jeffpearsall I'll toss a fix up to npm this afternoon thanks a ton for this!

**Comment by rodrigobdz** [comment]
@cosmocochrane1 thanks for getting on top of this.

**Pull request merged**
